In [1]:
import pandas as pd
import folium
import webbrowser
from datetime import datetime

In [33]:
zoom_start = 8

In [2]:
myf_csv = '/Users/Vitaly/Documents/OnSail/boats/petsamo/MARK 3.csv'

In [3]:
myf_json = '/Users/Vitaly/Documents/OnSail/boats/petsamo/MARK 3.json'

In [4]:
with open(myf_csv, 'r') as f:
    contents = f.read()

with open(myf_csv, 'w') as f:
    f.write(contents.replace(';', ';,'))

In [6]:
df=pd.read_csv(myf_csv)

In [7]:
df.drop(0, axis=0, inplace=True)
df

                     position;  Unnamed: 1  Unnamed: 2                heure
1   03°08.544 S  131°23.943 E;         NaN         NaN  27/01/2023 16:20:00
2   01°35.046 S  130°52.393 E;         NaN         NaN  28/01/2023 09:40:00
3   01°23.006 S  130°53.429 E;         NaN         NaN  28/01/2023 11:35:00
4   01°18.102 S  130°41.370 E;         NaN         NaN  28/01/2023 13:35:00
5   00°59.650 S  130°21.586 E;         NaN         NaN  28/01/2023 17:30:00
6   00°38.227 S  130°08.695 E;         NaN         NaN  28/01/2023 20:35:00
7   00°18.823 N  129°51.036 E;         NaN         NaN  29/01/2023 05:45:00
8   00°58.550 N  129°52.363 E;         NaN         NaN  29/01/2023 12:05:00
9   02°41.723 N  130°03.352 E;         NaN         NaN  30/01/2023 01:30:00
10  08°49.160 N  128°24.977 E;         NaN         NaN  31/01/2023 16:05:00
11  12°40.708 N  125°06.708 E;         NaN         NaN  01/02/2023 16:15:00
12  12°49.810 N  124°47.929 E;         NaN         NaN  01/02/2023 18:05:00
13  12°56.272 N  124°21.632 E;         NaN         NaN  01/02/2023 20:25:00
14  12°28.788 N  124°05.408 E;         NaN         NaN  01/02/2023 23:15:00
15  12°45.224 N  123°31.519 E;         NaN         NaN  02/02/2023 02:15:00
16  12°39.663 N  123°29.640 E;         NaN         NaN  02/02/2023 02:45:00
17  12°40.860 N  123°16.186 E;         NaN         NaN  02/02/2023 04:00:00
18  11°59.535 N  122°51.618 E;         NaN         NaN  02/02/2023 08:20:00
19  11°58.856 N  122°51.778 E;         NaN         NaN  02/02/2023 08:25:00
20  12°00.804 N  121°53.508 E;         NaN         NaN  02/02/2023 13:05:00
21  11°44.604 N  121°48.762 E;         NaN         NaN  02/02/2023 14:20:00

In [21]:
df_json = pd.read_json(myf_json)
df_json.head()

      nom                                             tracks
0  MARK 3  [1674774599, 132266.2716666667, -3798.6600000000]
1  MARK 3  [1674841500, 131399.0547330466, -3142.3987242898]
2  MARK 3  [1674904800, 130873.2162955628, -1584.1051662000]
3  MARK 3  [1674921000, 130890.4818298041, -1383.4313373375]
4  MARK 3  [1674927600, 130689.4991242859, -1301.6945802764]

In [22]:
df_json.drop('nom', axis=1, inplace=True)
df_json.head()
df_json.drop(0, axis=0, inplace=True)

In [23]:
df_json['epoch'] = [df_json['tracks'][idx][0] for idx in df_json.index]
df_json['Lon'] = [float(df_json['tracks'][idx][1])/1000 for idx in df_json.index]
df_json['Lat'] = [float(df_json['tracks'][idx][2])/1000 for idx in df_json.index]
df_json.drop('tracks', axis=1, inplace=True)
df_json.head()

        epoch         Lon       Lat
1  1674841500  131.399055 -3.142399
2  1674904800  130.873216 -1.584105
3  1674921000  130.890482 -1.383431
4  1674927600  130.689499 -1.301695
5  1674941700  130.359765 -0.994175

In [24]:
df_json['epoch']=df_json['epoch'].astype(int)

In [25]:
df_json['ETA'] = [datetime.fromtimestamp(x).strftime("%d-%h %H:%M") for x in df_json['epoch']]
df_json.drop('epoch', axis=1, inplace=True)

In [26]:
df_json

           Lon        Lat           ETA
1   131.399055  -3.142399  27-Jan 12:45
2   130.873216  -1.584105  28-Jan 06:20
3   130.890482  -1.383431  28-Jan 10:50
4   130.689499  -1.301695  28-Jan 12:40
5   130.359765  -0.994175  28-Jan 16:35
6   130.144909  -0.637116  28-Jan 20:55
7   129.850605   0.313718  29-Jan 07:50
8   129.872710   0.975833  29-Jan 13:40
9   130.055861   2.695391  30-Jan 02:55
10  128.416287   8.819326  31-Jan 17:15
11  125.111797  12.678474  01-Feb 18:30
12  124.798824  12.830164  01-Feb 20:15
13  124.360536  12.937869  01-Feb 22:15
14  124.090137  12.479802  02-Feb 01:00
15  123.525316  12.753732  02-Feb 03:50
16  123.493997  12.661048  02-Feb 04:20
17  123.269775  12.681001  02-Feb 05:40
18  122.860301  11.992248  02-Feb 10:00
19  122.862959  11.980935  02-Feb 10:00
20  121.891801  12.013393  02-Feb 14:15
21  121.812700  11.743400  02-Feb 15:30

In [30]:
points = [(df_json.iloc[i]['Lat'], df_json.iloc[i]['Lon']) for i in range(len(df_json.index))]

In [34]:
mymap = folium.Map(location=[df_json.iloc[1]['Lat'], df_json.iloc[1]['Lon']], zoom_start=zoom_start)

In [37]:
folium.PolyLine(points).add_to(mymap)
mymap