In [1]:
from lib.common import *
from lib.boat import boat

In [15]:
boat1=boat('Petsamo')
boat1.getdata()
boat1.show(full=True)
boat1.save_current_sail_data()

PETSAMO
----------------
lat: -26.94989
lon: 153.94365


mainsail:        X
mizzen:          X
genaker:
mizzen staysail: X
nr.1:
nr.2:            X
nr.3:
stormjib:


hdg: 348
spd: 8
cog: 349
sog: 7
whlm: -0.13
tws: 24
twa: -169
twd: 179
aws: 17
awa: -164

In [13]:
boat2=boat('Azohen Vey')
boat2.getdata()
boat2.show(full=True)
boat2.save_current_sail_data()

AZOHEN VEY
----------------
lat: 8.59241
lon: -79.59721


mainsail:        X
genoa:           X
jib:
nr.4:


hdg: 40
spd: 0
cog: 44
sog: 0
whlm: -0.06
tws: 8
twa: -44
twd: 356
aws: 11
awa: -28

In [16]:
df1=boat1.get_sail_data()

In [17]:
df1

,tws,spd,twd,twa,sails
2023-01-06 00:40:08.983560562,11.8032,3.9247,178.964,-168.615,"[Mainsail, Mizzen, Mizzen staysail, Nr.2]"
2023-01-06 00:41:23.279702425,11.8032,3.9247,178.964,-168.615,"[Mainsail, Mizzen, Mizzen staysail, Nr.2]"
2023-01-06 00:42:09.562597275,11.8032,3.9247,178.964,-168.615,"[Mainsail, Mizzen, Mizzen staysail, Nr.2]"
2023-01-06 00:42:11.740645647,11.8032,3.9247,178.964,-168.615,"[Mainsail, Mizzen, Mizzen staysail, Nr.2]"

In [18]:
df2=boat2.get_sail_data()
df2

                                  tws  spd      twd  twa              sails
2023-01-06 00:40:09.550222635  3.7737    0  355.898  -44  [Mainsail, Genoa]
2023-01-06 00:41:58.204790115  3.7737    0  355.898  -44  [Mainsail, Genoa]
2023-01-06 00:42:03.864034891  3.7737    0  355.898  -44  [Mainsail, Genoa]
2023-01-06 00:42:06.479136705  3.7737    0  355.898  -44  [Mainsail, Genoa]